on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-*"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build

    # Axis.Luna.Automata
    - name: Pack
      run: dotnet pack ./Axis.Luna.Automata/Axis.Luna.Automata.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Luna.Automata.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Luna.BitSequence
    - name: Pack
      run: dotnet pack ./Axis.Luna.BitSequence/Axis.Luna.BitSequence.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Luna.BitSequence.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Luna.Numerics
    - name: Pack
      run: dotnet pack ./Axis.Luna.Numerics/Axis.Luna.Numerics.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Luna.Numerics.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Luna.Optional
    - name: Pack
      run: dotnet pack ./Axis.Luna.Optional/Axis.Luna.Optional.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Luna.Optional.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Luna.Result
    - name: Pack
      run: dotnet pack ./Axis.Luna.Result/Axis.Luna.Result.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Luna.Result.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Luna.Unions
    - name: Pack
      run: dotnet pack ./Axis.Luna.Unions/Axis.Luna.Unions.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Luna.Unions.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Luna.Common
    - name: Pack
      run: dotnet pack ./Axis.Luna.Common/Axis.Luna.Common.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Luna.Common.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Luna.Factory.Contracts
    - name: Pack
      run: dotnet pack ./Axis.Luna.Factory.Contracts/Axis.Luna.Factory.Contracts.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Luna.Factory.Contracts.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Luna.Extensions
    - name: Pack
      run: dotnet pack ./Axis.Luna.Extensions/Axis.Luna.Extensions.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Luna.Extensions.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Luna.FInvoke
    - name: Pack
      run: dotnet pack ./Axis.Luna.FInvoke/Axis.Luna.FInvoke.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Luna.FInvoke.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}
